/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.views.panel;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.UIManager;
import vapi.ValidatorMaster;

/**
 *
 * @author Usuario
 */
public class pnlMoney extends javax.swing.JPanel {

    /**
     * Creates new form pnlMoney
     */
    public pnlMoney() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnConvertir = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lnlTitle = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        lblcomboBox = new javax.swing.JLabel();
        cmbMoney = new javax.swing.JComboBox<>();
        txtResultado = new javax.swing.JTextField();
        lblResultado = new javax.swing.JLabel();
        lblElije = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        btnConvertir.setText("Convertir");
        btnConvertir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnConvertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConvertirActionPerformed(evt);
            }
        });

        btnNuevo.setText("Limpiar");
        btnNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnConvertir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevo)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnConvertir)))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 267, 400, 40));

        lnlTitle.setText("Ingresa los datos a Convertir");
        add(lnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        txtMoney.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txtMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMoneyActionPerformed(evt);
            }
        });
        txtMoney.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMoneyKeyPressed(evt);
            }
        });
        add(txtMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 140, -1));

        lblcomboBox.setText("Elije una opción");
        add(lblcomboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 80, 20));

        cmbMoney.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "c$   -->   $", "$   -->   c$" }));
        cmbMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cmbMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMoneyActionPerformed(evt);
            }
        });
        add(cmbMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 100, -1));

        txtResultado.setEditable(false);
        txtResultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtResultadoActionPerformed(evt);
            }
        });
        add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 140, -1));

        lblResultado.setText("Resultado");
        add(lblResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, -1, -1));
        add(lblElije, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 20, 20));
    }// </editor-fold>//GEN-END:initComponents

    private void txtMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMoneyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMoneyActionPerformed

    private void txtMoneyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMoneyKeyPressed
        ValidatorMaster.soloNumeros(txtMoney);
        txtMoney.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    }//GEN-LAST:event_txtMoneyKeyPressed

    private void cmbMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMoneyActionPerformed

    }//GEN-LAST:event_cmbMoneyActionPerformed

    private void txtResultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtResultadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResultadoActionPerformed

    private void btnConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConvertirActionPerformed
        if (txtMoney.getText().equals("")) {
            txtMoney.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        } else {
            double money = Double.parseDouble(txtMoney.getText());

            if (cmbMoney.getSelectedItem().toString().equals("$   -->   c$")) {
                double cordobas = (35.14) * money;
                txtResultado.setText(String.valueOf(cordobas));
                lblElije.setText("c$");
            } else if (cmbMoney.getSelectedItem().toString().equals("c$   -->   $")) {
                double bucks = (money / 35.14);
                txtResultado.setText(String.valueOf(bucks));
                lblElije.setText("$");
            }
        }
    }//GEN-LAST:event_btnConvertirActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        txtMoney.setText("");
        txtResultado.setText("");
        lblElije.setText("");
    }//GEN-LAST:event_btnNuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConvertir;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cmbMoney;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblElije;
    private javax.swing.JLabel lblResultado;
    private javax.swing.JLabel lblcomboBox;
    private javax.swing.JLabel lnlTitle;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
