/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.views.panel;

import backend.dao.implementation.VehicleTableModel;
import java.awt.Rectangle;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class PnlVehicleView extends javax.swing.JPanel {

    private VehicleTableModel vehicleTableModel;

    /**
     * Creates new form PnlVehicleView
     */
    public PnlVehicleView() {
        initComponents();
    }

    public void setVehicleTableModel(VehicleTableModel vehicleTableModel) {
        this.vehicleTableModel = vehicleTableModel;
        if (vehicleTableModel == null) {
            return;
        }
        tbVehicles.setModel(vehicleTableModel);
        setSelectedRow(0);
        setPreferredWidthColumns(3, 5, 150);
        setPreferredWidthColumns(6, 6, 200);
    }
    
    String[] titulos = {"Stock Number","Year","Make","Model","Style","VIN","EColor","IColor","Miles","Price","Transmission","Engine","Image","Status"};
    DefaultTableModel dtm = new DefaultTableModel(null, titulos);
    String filas[] = {};
    
    public void setSelectedRow(int row){
        tbVehicles.getSelectionModel().setSelectionInterval(row, row);
    }
    
    public void setScrollRectVisible(int row){
        tbVehicles.scrollRectToVisible(new Rectangle(tbVehicles.getCellRect(row, 0, true)));
    }
    
    private void setPreferredWidthColumns(int start, int end, int width){
        for (int i = start; i <= end; i++) {
            tbVehicles.getColumnModel().getColumn(i).setPreferredWidth(width);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbVehicles = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.insets = new java.awt.Insets(1, 4, 1, 4);
        jPanel1.add(jTextField1, gridBagConstraints);

        jLabel1.setText("Buscar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        jPanel1.add(jLabel1, gridBagConstraints);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        tbVehicles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tbVehicles);

        jPanel2.add(jScrollPane2, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable tbVehicles;
    // End of variables declaration//GEN-END:variables
}
