/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.text.AttributeSet;
import javax.swing.text.Element;
import javax.swing.text.MutableAttributeSet;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import view.ClassImplements.IOString;
import view.views.panel.pnlTextEditor;
import say.swing.JFontChooser;

/**
 *
 * @author Usuario
 */
public class FrmEditor extends javax.swing.JFrame {

    private int countTab;
    private FileNameExtensionFilter fileNameFileFilter;
    private JFileChooser fileChooser;
    private IOString ioString;
    private JFontChooser fontChooser;

    /**
     * Creates new form FrmEditor
     */
    public FrmEditor() {
        countTab = 1;
        fileNameFileFilter = new FileNameExtensionFilter("*txt", "txt");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnCloseTab = new javax.swing.JButton();
        tglBold = new javax.swing.JToggleButton();
        tglJustify = new javax.swing.JToggleButton();
        tbpContent = new javax.swing.JTabbedPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnINew = new javax.swing.JMenuItem();
        mnIOpen = new javax.swing.JMenuItem();
        mnISave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem1 = new javax.swing.JMenuItem();
        formatMenu = new javax.swing.JMenu();
        mniTextFormat = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Editor de Texto");

        btnCloseTab.setText("X");
        btnCloseTab.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCloseTab.setFocusable(false);
        btnCloseTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCloseTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnCloseTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseTabActionPerformed(evt);
            }
        });
        jToolBar1.add(btnCloseTab);

        tglBold.setText("Bold");
        tglBold.setFocusable(false);
        tglBold.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglBold.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tglBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBoldActionPerformed(evt);
            }
        });
        jToolBar1.add(tglBold);

        tglJustify.setText("Justify");
        tglJustify.setFocusable(false);
        tglJustify.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tglJustify.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(tglJustify);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);
        getContentPane().add(tbpContent, java.awt.BorderLayout.CENTER);

        mnFile.setText("File");

        mnINew.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnINew.setText("New");
        mnINew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnINewActionPerformed(evt);
            }
        });
        mnFile.add(mnINew);

        mnIOpen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnIOpen.setText("Open...");
        mnIOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnIOpenActionPerformed(evt);
            }
        });
        mnFile.add(mnIOpen);

        mnISave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        mnISave.setText("Save");
        mnISave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnISaveActionPerformed(evt);
            }
        });
        mnFile.add(mnISave);
        mnFile.add(jSeparator1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem1.setText("Exit");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnFile.add(jMenuItem1);

        jMenuBar1.add(mnFile);

        formatMenu.setText("Edit");
        formatMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formatMenuActionPerformed(evt);
            }
        });

        mniTextFormat.setText("Text Format");
        mniTextFormat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mniTextFormatActionPerformed(evt);
            }
        });
        formatMenu.add(mniTextFormat);

        jMenuBar1.add(formatMenu);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnINewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnINewActionPerformed
        pnlTextEditor pnlTextEditor = new pnlTextEditor();
        tbpContent.addTab("Editor" + countTab++, pnlTextEditor);
    }//GEN-LAST:event_mnINewActionPerformed

    private void btnCloseTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseTabActionPerformed
        if (tbpContent.getComponentCount() <= 0) {
            return;
        }
        int option = JOptionPane.showInternalConfirmDialog(null, "Are you sure to delete this tab?", "Confirmation dialog", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

        if (option == 1) {
            return;
        }

        int index = tbpContent.getSelectedIndex();
        tbpContent.remove(index);
    }//GEN-LAST:event_btnCloseTabActionPerformed

    private void mnISaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnISaveActionPerformed
        pnlTextEditor pnlEditor = (pnlTextEditor) tbpContent.getSelectedComponent();
        int index = tbpContent.getSelectedIndex();
        if (pnlEditor == null) {
            return;
        }
        try {
            int option = getFileChooser().showSaveDialog(this);

            if (option == JFileChooser.CANCEL_OPTION) {
                return;
            }

            File file = getFileChooser().getSelectedFile();
            ioString = new IOString(file);

            ioString.writeString(pnlEditor.getTxtpEditor().getText(), false);

            tbpContent.setTitleAt(index, file.getName());
        } catch (IOException ex) {
            Logger.getLogger(FrmEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mnISaveActionPerformed

    private void mnIOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnIOpenActionPerformed
        int option = getFileChooser().showOpenDialog(this);

        if (option == JFileChooser.CANCEL_OPTION) {
            return;
        }

        File file = getFileChooser().getSelectedFile();
        ioString = new IOString(file);

        pnlTextEditor pnlEditor = new pnlTextEditor();
        try {
            pnlEditor.getTxtpEditor().setText(ioString.readString());
        } catch (IOException ex) {
            Logger.getLogger(FrmEditor.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbpContent.addTab(file.getName(), pnlEditor);

    }//GEN-LAST:event_mnIOpenActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void formatMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formatMenuActionPerformed
        pnlTextEditor pnlEditor = (pnlTextEditor) tbpContent.getSelectedComponent();
        if (pnlEditor == null) {
            return;
        }

        int option = getFontChooser().showDialog(this);
        if (option == JFontChooser.CANCEL_OPTION) {
            return;
        }

        String text = pnlEditor.getTxtpEditor().getSelectedText();
        if (text == null) {
            return;
        }

        Font font = getFontChooser().getSelectedFont();
        int start = pnlEditor.getTxtpEditor().getSelectionStart();
        StyledDocument style = pnlEditor.getTxtpEditor().getStyledDocument();
        pnlEditor.getTxtpEditor().setStyledDocument(getStyledDocuemt(font, style, start, text.length()));
    }//GEN-LAST:event_formatMenuActionPerformed

    private void tglBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBoldActionPerformed
        pnlTextEditor pnlEditor = (pnlTextEditor) tbpContent.getSelectedComponent();
        if (pnlEditor == null) {
            return;
        }

        String text = pnlEditor.getTxtpEditor().getSelectedText();
        if (text == null) {
            return;
        }

        int start = pnlEditor.getTxtpEditor().getSelectionStart();
        StyledDocument style = pnlEditor.getTxtpEditor().getStyledDocument();

        Font font = new Font(Font.SERIF, tglBold.isSelected() ? Font.BOLD : Font.PLAIN, 12);
        pnlEditor.getTxtpEditor().setStyledDocument(getStyledDocuemt(font, style, start, text.length()));
    }//GEN-LAST:event_tglBoldActionPerformed

    private void mniTextFormatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mniTextFormatActionPerformed
        pnlTextEditor pnlEditor = (pnlTextEditor) tbpContent.getSelectedComponent();
        if (pnlEditor == null) {
            return;
        }

        int option = getFontChooser().showDialog(this);
        if (option == JFontChooser.CANCEL_OPTION) {
            return;
        }

        String text = pnlEditor.getTxtpEditor().getSelectedText();
        if (text == null) {
            return;
        }

        Font font = getFontChooser().getSelectedFont();
        int start = pnlEditor.getTxtpEditor().getSelectionStart();
        StyledDocument style = pnlEditor.getTxtpEditor().getStyledDocument();
        pnlEditor.getTxtpEditor().setStyledDocument(getStyledDocuemt(font, style, start, text.length()));
    }//GEN-LAST:event_mniTextFormatActionPerformed

    private StyledDocument getStyledDocuemt(Font font, StyledDocument style, int start, int length) {
        MutableAttributeSet attributeSet = getMutableAttributeSet(style, start);

        attributeSet.addAttribute(StyleConstants.Bold, font.isBold());
        attributeSet.addAttribute(StyleConstants.Italic, font.isItalic());
        attributeSet.addAttribute(StyleConstants.Size, font.getSize());
        attributeSet.addAttribute(StyleConstants.Family, font.getFamily());
        attributeSet.addAttribute(StyleConstants.Alignment, StyleConstants.ALIGN_JUSTIFIED);

        style.setCharacterAttributes(start, length, attributeSet, true);

        return style;
    }

    private MutableAttributeSet getMutableAttributeSet(StyledDocument style, int start) {
        Element element = style.getCharacterElement(start);
        AttributeSet as = element.getAttributes();

        return new SimpleAttributeSet(as.copyAttributes());
    }

    private JFileChooser getFileChooser() {
        if (fileChooser == null) {
            fileChooser = new JFileChooser();
            fileChooser.addChoosableFileFilter(fileNameFileFilter);
            fileChooser.setFileFilter(fileNameFileFilter);
        }

        return fileChooser;
    }

    private JFontChooser getFontChooser() {
        if (fontChooser == null) {
            fontChooser = new JFontChooser();
        }
        return fontChooser;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEditor.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEditor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseTab;
    private javax.swing.JMenu formatMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnINew;
    private javax.swing.JMenuItem mnIOpen;
    private javax.swing.JMenuItem mnISave;
    private javax.swing.JMenuItem mniTextFormat;
    private javax.swing.JTabbedPane tbpContent;
    private javax.swing.JToggleButton tglBold;
    private javax.swing.JToggleButton tglJustify;
    // End of variables declaration//GEN-END:variables
}
