/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.BorderLayout;
import view.views.panel.*;

/**
 *
 * @author Sistemas-03
 */
public class StartFrame extends javax.swing.JFrame {

    private pnlCalculadora pnlCalculadora;
    private pnlTemperatura pnlTemperatura;
    private pnlMoney pnlMoney;

    /**
     * Creates new form StartFrame
     */
    public StartFrame() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlLeft = new javax.swing.JPanel();
        btnCalculadora = new javax.swing.JButton();
        btnTemperatura = new javax.swing.JButton();
        btnMoney = new javax.swing.JButton();
        pnlContent = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My App");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new java.awt.BorderLayout(3, 2));

        pnlLeft.setBackground(new java.awt.Color(153, 153, 153));
        pnlLeft.setPreferredSize(new java.awt.Dimension(120, 100));
        pnlLeft.setLayout(new java.awt.GridLayout(3, 1, 2, 3));

        btnCalculadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Programacion2\\src\\main\\java\\Source\\imgCalculator.png")); // NOI18N
        btnCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalculadoraActionPerformed(evt);
            }
        });
        pnlLeft.add(btnCalculadora);

        btnTemperatura.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Programacion2\\src\\main\\java\\Source\\imgTemperature.png")); // NOI18N
        btnTemperatura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTemperatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTemperaturaActionPerformed(evt);
            }
        });
        pnlLeft.add(btnTemperatura);

        btnMoney.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\Programacion2\\src\\main\\java\\Source\\imgMoney.png")); // NOI18N
        btnMoney.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoneyActionPerformed(evt);
            }
        });
        pnlLeft.add(btnMoney);

        getContentPane().add(pnlLeft, java.awt.BorderLayout.LINE_START);

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.BorderLayout());
        getContentPane().add(pnlContent, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(416, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculadoraActionPerformed
        pnlContent.removeAll();
        pnlContent.revalidate();
        pnlContent.repaint();
        if (pnlCalculadora == null) {
            pnlCalculadora = new pnlCalculadora();
        }
        if (pnlContent.getComponentCount() > 0) {
            pnlContent.remove(0);
        }

        pnlContent.add(pnlCalculadora, BorderLayout.CENTER);
        this.setVisible(true);
        //this.validate(); TAMBIEN SE PUEDE USAR PARA LIMPIAR EL BUFFER
    }//GEN-LAST:event_btnCalculadoraActionPerformed

    private void btnTemperaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTemperaturaActionPerformed
        pnlContent.removeAll();
        pnlContent.revalidate();
        pnlContent.repaint();
        if (pnlTemperatura == null) {
            pnlTemperatura = new pnlTemperatura();
        }
        if (pnlContent.getComponentCount() > 0) {
            pnlContent.remove(0);
        }

        pnlContent.add(pnlTemperatura, BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_btnTemperaturaActionPerformed

    private void btnMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoneyActionPerformed
        pnlContent.removeAll();
        pnlContent.revalidate();
        pnlContent.repaint();
        if (pnlMoney == null) {
            pnlMoney = new pnlMoney();
        }
        if (pnlContent.getComponentCount() > 0) {
            pnlContent.remove(0);
        }

        pnlContent.add(pnlMoney, BorderLayout.CENTER);
        this.setVisible(true);
    }//GEN-LAST:event_btnMoneyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StartFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StartFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalculadora;
    private javax.swing.JButton btnMoney;
    private javax.swing.JButton btnTemperatura;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlLeft;
    // End of variables declaration//GEN-END:variables
}
